### ISSUE TITLE
Lines of text change line spacing between OSes

### ISSUE THREAD

**Issue by mvxt** [excalidraw/excalidraw#1815]
**Problem Summary/Recreation**
- Chrome 83.0.4103.116 on macOS 10.15.5 Catalina
- Chrome 83.0.4103.116 on Windows 10 v1909

I've been working on a project for a little while, and I switch between the two above computers to do work. One is a Windows OS and the other is macOS. I use a lot of new lines for multi-line text in my diagrams (Shift+Enter).

When I finish and push my changes on Windows, then pull changes and open the same Excalidraw file on the browser on my mac, the line spacing changes.

You can recreate this by opening one of the `*.excalidraw` roadmap files in this repository:
https://github.com/Static-Void-Academy/complete-software-roadmap

I know that Windows / DOS uses both CR-LF vs. *nix which uses just LF. Might that be the issue here?

**Comment by dwelle** [comment]
We're normalizing CRLF → LF on render, so EOL shouldn't be it. I'm checking your source files, and there aren't even any `\r` line endings in the texts.

I'm not on Mac so can't check. Are you using Firefox in one of the cases? I can reproduce spacing issues, but not vertical, but horizontal, when editing the indented text on Firefox.

The above specific issue is fixed in my latest PR: https://github.com/excalidraw/excalidraw/pull/1783

You can check the preview if you can reproduce the other issues: https://excalidraw-37phjuqal.vercel.app/

**Comment by mvxt** [comment]
> Are you using Firefox in one of the cases?

No, but I was able to reproduce the issues both on Firefox and on Chrome at that preview deployment. It could potentially be Mac. Does the line spacing depend on screen resolution at all? That's the only other difference I can think of between my computers. See the GIFs below:

## On Chrome, Preview (https://excalidraw-37phjuqal.vercel.app)
![Chrome-Preview](https://user-images.githubusercontent.com/2441695/85524776-b484ac80-b5c5-11ea-8a25-a51e16f679d6.gif)

## Same thing on Firefox, Preview (https://excalidraw-37phjuqal.vercel.app)
![Firefox-Preview](https://user-images.githubusercontent.com/2441695/85525002-e4cc4b00-b5c5-11ea-9237-881fe88b6ae9.gif)

> Great work on the diagrams btw.

Thank you!

**Comment by dwelle** [comment]
> Does the line spacing depend on screen resolution at all? That's the only other difference I can think of between my computers. See the GIFs below:

Maybe... but it should reproduce right on the higher-res system during edit if the editor doesn't account for that :thinking:.  I'll try to investigate.

**Comment by dwelle** [comment]
It seems like a line height issue. I've tried to fix it in https://excalidraw-my3vj8whu.vercel.app/, but I've been told it's still affected.

It supposedly happens only on initial edit, and goes away after you start typing. Also, do I understand that the preview (the one I posted in this comment) is "more" buggier (as in affects more browsers) than what's deployed on excalidraw.com right now?

**Comment by mvxt** [comment]
@dwelle Thanks for your patience.

I tried out your preview (https://excalidraw-my3vj8whu.vercel.app/), but I can confirm that the problem is still there, and in addition, it still persists even after I type and save changes. Happens on both Firefox and Chrome:

![Persist](https://user-images.githubusercontent.com/2441695/85687415-16104e00-b68e-11ea-8420-c34c431fe6c5.gif)

And no, the behavior of the preview(s) and the currently-deployed stable Excalidraw is the same:
- On Firefox, double-clicking the multi-line textboxes both changes the line spacing and removes leading white spaces, which is probably what you were seeing re:horizontal spacing issues
- On Chrome, double-clicking the multi-line textboxes preserves the leading white spaces (e.g. horizontal spacing) but changes the line spacing.

**Comment by dwelle** [comment]
> On Firefox, double-clicking the multi-line textboxes both changes the line spacing and removes leading white spaces, which is probably what you were seeing re:horizontal spacing issues

That's a new one. Are we talking about stable or also the preview?

Last I checked, those leading spaces were actual spaces, not tabs, so can't explain the behavior either way.

**Comment by mvxt** [comment]
>That's a new one. Are we talking about stable or also the preview?

Hm. I'm not sure what changed here, but it looks like on Firefox I no longer see horizontal spacing issues for both preview and stable deployments. So it looks like for both Chrome and Firefox, and for preview and stable deployments, it's only a line spacing issue now.

Incidentally, I tried testing the opposite direction: creating an Excalidrawing on macOS and then opening it on Windows. The line-spacing changes the opposite direction. 🤣 

![mac_to_windows](https://user-images.githubusercontent.com/2441695/85805897-cf146e00-b70a-11ea-9e84-d0a809e23461.gif)

So there might be some hard-coded values somewhere. I tried again by changing the resolution on my Windows screen to mirror the Mac (1440 x 900) and the line spacing changes still happened. So it looks like it's depending on something other than screen resolution.

**Comment by dwelle** [comment]
Could you please share in any way two files with the same text, once created on the mac, and one created on mac? I could try to figure out what's the issue from the JSON data.

**Comment by mvxt** [comment]
Here you go:

## Created on Mac:
```
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "LcRYq_et1YXpVKNagM8Iu",
      "type": "text",
      "x": 668.5,
      "y": 160,
      "width": 411,
      "height": 100,
      "angle": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "seed": 901411379,
      "version": 148,
      "versionNonce": 887525853,
      "isDeleted": false,
      "text": "Testing testing 123\n   Hello this is a new line indented inward\n   Another line indented (with 3 spaces)\n      Now 6 spaces indented",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "baseline": 93
    }
  ],
  "appState": {
    "viewBackgroundColor": "#ffffff",
    "gridSize": null
  }
}
```

## Created on Windows:
```
{
  "type": "excalidraw",
  "version": 2,
  "source": "https://excalidraw.com",
  "elements": [
    {
      "id": "rgERhLKoTLBXiUQurg771",
      "type": "text",
      "x": 885,
      "y": 356.5,
      "width": 411,
      "height": 128,
      "angle": 0,
      "strokeColor": "#000000",
      "backgroundColor": "transparent",
      "fillStyle": "hachure",
      "strokeWidth": 1,
      "strokeStyle": "solid",
      "roughness": 1,
      "opacity": 100,
      "groupIds": [],
      "seed": 1516563968,
      "version": 147,
      "versionNonce": 580464128,
      "isDeleted": false,
      "text": "Testing testing 123\n   Hello this is a new line indented inward\n   Another line indented (with 3 spaces)\n      Now 6 spaces indented",
      "fontSize": 20,
      "fontFamily": 1,
      "textAlign": "left",
      "verticalAlign": "top",
      "baseline": 119
    }
  ],
  "appState": {
    "viewBackgroundColor": "#ffffff",
    "gridSize": null
  }
}
```

When I diffed the two files I noticed that the two differences of interest were the "height" and "baseline" parameters. I tried manually modifying them in Vim and saw that these two parameters were what affect the appearance.

It looks like we can narrow down into checking what sets those default "height" and "baseline" parameters
