### ISSUE TITLE
wrong colors handling in dark theme

### ISSUE THREAD

**Issue by Alcarmor** [excalidraw/excalidraw#6669]
while using the dark theme the yellow color #ffff00 is showed much more similar to #313100
switching to the standard theme, the yellow color is showed properly instead

![image](https://github.com/excalidraw/excalidraw/assets/32539566/3feebe23-358b-454e-b380-8db8c345b08f)
![image](https://github.com/excalidraw/excalidraw/assets/32539566/18123857-5911-435b-8a9f-041ae1581acd)

**Comment by Thedineshk24** [comment]
hey @Alcarmor , I've fixed issue of yellow color not looks like yellow by adding more brighter yellow color, although keep in mind below things, which will help you understand, why #ffff00 is not looked like yellow in dark mode.

ANS: In the dark mode, the color #FFFF00 (hex code for yellow) may not appear as a vibrant yellow due to the contrast and color adjustments applied by the dark theme. Dark themes typically use darker background colors and adjust the contrast of text and elements to improve readability.

**Comment by Verbina29** [comment]
Please fix this, the color adjustments probably shouldn't be applied when explicitly entering in a hex code.

**Comment by soulis-1256** [comment]
The choice of applying color inverting filters to the whole app is objectively wrong, at least the way it is implemented now. I propose the following:
1. Rename the current dark mode to "Read mode".
2. Create a new, proper dark mode, that will only change the colors of the UI elements and the canvas background (as for "performance", just don't apply filters in this mode, or apply filters to the UI elements and just define a new set of colors for the canvas background).
3. Set the new dark mode as the "default" dark mode, to prevent people coming back to this issue.

I think will cover the best of both worlds. Keep up the good work with Excalidraw.

**Comment by IamSmeagol** [comment]
The fact that manually entered HEX colors get automatically changed to something else is very annoying. Please make it so that manual HEX codes show as expected and that dark theme by default only changes the UI not the manual colors.

**Comment by maks244** [comment]
This issue still exists, and it's very annoying that it took 5m of sanity checking to find out I was in fact putting in the correct hex code

**Comment by MathewAddala** [comment]
## Proposed Solution

After reviewing this issue and the previous PR #6674, I'd like to suggest a more comprehensive solution to preserve manually entered hex codes while maintaining dark theme aesthetics.

### Root Cause
The current dark mode implementation applies CSS filters (`invert()` and `hue-rotate()`) to the entire canvas, which transforms all colors including those explicitly chosen by users. This causes `#ffff00` (yellow) to appear as `#313100` (dark olive).

### Proposed Fix

**Option 1: Selective Filter Application (Recommended)**
- Apply dark mode filters only to UI elements and canvas background
- Store user-selected colors in their original hex format with a flag indicating "user-selected"
- Render user-selected element colors without applying inversion filters
- This preserves color fidelity for intentional user choices

**Implementation approach:**
```javascript
// In color utility functions
const applyDarkModeColor = (color, isUserSelected = false) => {
  if (isUserSelected) {
    return color; // Preserve original hex
  }
  // Apply dark mode transformation only for default palette colors
  return transformColorForDarkMode(color);
};
```

**Option 2: Dual Color Storage**
- Store both the original hex and the display hex
- When in dark mode, check if color was manually entered
- If manually entered, use original hex; otherwise apply transformation

### Benefits
- Preserves WCAG color standards when users intentionally select specific colors
- Maintains dark theme benefits for default UI elements
- Backwards compatible with existing drawings
- Fixes the core UX issue where manual hex entry doesn't match displayed color

I'm happy to work on a PR implementing Option 1 if this approach sounds good to the maintainers. Let me know your thoughts!

**Comment by KaKi87** [comment]
Hi @dwelle, @mtolmacs,
Any news on this please ? 🙏 
Thank you

**Comment by ygg2** [comment]
The color shifting can especially be an issue when marking up an image since a person may be writing with a color that's very distinct on top of the image in one mode, while collaborators cannot read it in the other mode. I imagine this happening for the canvas background is a reason that the colors are shifted in the first place, so maybe the suggested Option 2 is the way to go, or a toggle on the element for whether the color should adapt based on the mode.

**Comment by l3oytoys** [comment]
3 year and its didn't fix?
